# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0002_language_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpage',
            name='images',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
