# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0005_auto_20170329_0321'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpage',
            name='related_projects',
            field=models.ManyToManyField(blank=True, related_name='_projectpage_related_projects_+', to='Projects.ProjectPage'),
        ),
    ]
