# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-30 01:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0007_auto_20170329_1432'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectpage',
            old_name='pageTitle',
            new_name='page_title',
        ),
        migrations.AddField(
            model_name='projectpage',
            name='external_media',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='quick_facts',
            field=models.TextField(blank=True, null=True),
        ),
    ]
