# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-30 01:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0008_auto_20170330_0119'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='slug',
            field=models.SlugField(default='No', max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projectpage',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
