# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-30 01:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0009_auto_20170330_0130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectpage',
            old_name='page_title',
            new_name='pageTitle',
        ),
    ]
