# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-30 01:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0010_auto_20170330_0134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpage',
            name='pageTitle',
            field=models.CharField(help_text='This is the title of the project', max_length=200),
        ),
    ]
