# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-30 01:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0011_auto_20170330_0152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpage',
            name='content',
            field=models.TextField(help_text='Markdown Enabled.'),
        ),
        migrations.AlterField(
            model_name='projectpage',
            name='external_media',
            field=models.TextField(blank=True, help_text='HTML Enabled', null=True),
        ),
        migrations.AlterField(
            model_name='projectpage',
            name='images',
            field=models.TextField(blank=True, help_text='Just the name and extension. The files must be in the correct static directory!', null=True),
        ),
        migrations.AlterField(
            model_name='projectpage',
            name='quick_facts',
            field=models.TextField(blank=True, help_text='HTML Enabled.', null=True),
        ),
    ]
