# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-17 03:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.CharField(default='No Description Provided', max_length=255),
            preserve_default=False,
        ),
    ]
