# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-06 02:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SearchOptionGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='option',
            name='parent_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PenaltyTracker.SearchOptionGroup'),
        ),
    ]
